            <main role="main" class="col-md-8 ml-sm-auto col-lg-9 px-md-4">
               <div class="overlayzada2"></div>
               <div class="box-geral m-2">
                  <h1 class="titlezada">POLÍTICAS DE PRIVACIDADE</h1>
                  <p>A presente Política de privacidade aplica-se a todos os produtos serviços disponibilizados pelo ELOJOB BRASIL. Por vezes, poderemos publicar avisos de privacidade específicos para produtos ou materiais do Centro de ajuda para explicar mais detalhadamente os nossos produtos.</p>
                  <p>Se tiver dúvidas relativamente a esta Política de privacidade, não hesite em contatar-nos através do nosso mural ou via e-mail para</p>
                  <p><a href="cdn-cgi/l/email-protection.html" class="__cf_email__" data-cfemail="472428293326332807222b282d2825253526342e2b6924282a692535">[email&#160;protected]</a></p>
                  <p>Informações recolhidas e modo de utilização</p>
                  <p>Poderemos recolher os seguintes tipos de informação:</p>
                  <p>• Informações que nos fornece – Quando subscreve uma conta ELOJOB BRASIL, solicitamos que nos forneça informações pessoais. Podemos combinar as informações que fornece ao abrigo da sua conta com informações provenientes de outros serviços do ELOJOB BRASIL ou de terceiros, para lhe proporcionarmos uma melhor experiência e para melhorarmos a qualidade dos nossos serviços. Para determinados serviços, podemos dar-lhe a oportunidade de recusar a combinação dessas informações. </p>
                  <p>• Informação de registo – Sempre que acede aos serviços do ELOJOB BRASIL através de um navegador de internet, de uma aplicação ou de outro cliente, os nossos servidores guardam automaticamente certas informações. Estes registros do servidor podem incluir informações, como o seu pedido da Web, a sua interação com um serviço, o endereço do protocolo de internet (IP) , o tipo de navegador, o idioma do navegador, a data e a hora do pedido e um ou mais cookies que podem identificar exclusivamente o seu navegador ou a sua conta.</p>
                  <p>Para além do anteriormente exposto, podemos utilizar a informação recolhida para:</p>
                  <p>• Disponibilizar, manter, proteger e melhorar os nossos serviços (incluindo serviços de publicidade) e desenvolver novos serviços; e</p>
                  <p>• Proteger os direitos ou as propriedades do ELOJOB BRASIL ou dos nossos utilizadores.</p>
                  <p>Se utilizarmos essas informações para fins diferentes dos que originaram a sua recolha, solicitaremos o seu consentimento antes de o fazermos.</p>
                  <p>O ELOJOB BRASIL processa as informações pessoais presentes nos nossos servidores em Miami Estados Unidos. </p>
                  <p>Partilha de informações</p>
                  <p>O ELOJOB BRASIL só partilha informações pessoais com outras empresas ou indivíduos externos ao ELOJOB BRASIL nas seguintes circunstâncias limitadas:</p>
                  <p>• Temos o seu consentimento. Solicitamos o consentimento ativo para a partilha de qualquer informação pessoal sensível.</p>
                  <p>• Estamos sinceramente convictos de que o acesso, utilização, preservação ou divulgação dessas informações é razoavelmente necessário para (a) cumprir qualquer lei ou regulamento aplicável, qualquer processo judicial ou pedido executório de organismo ou entidade do Estado, (b) executar os Termos de utilização aplicáveis, incluindo a investigação de potenciais violações dos mesmos, (c) detectar, impedir ou de outra forma resolver problemas técnicos, de segurança ou fraude, ou (d) proteger contra danos os direitos, as propriedades ou a segurança do ELOJOB BRASIL, dos seus utilizadores ou do público, nos termos exigidos ou permitidos por lei.</p>
                  <p>Se o ELOJOB BRASIL vier a estar envolvida num processo de fusão ou aquisição, ou em qualquer forma de venda dos seus ativos, em parte ou no todo, garantiremos a confidencialidade das informações pessoais envolvidas nessas transações e forneceremos um aviso antes de as informações pessoais serem transmitidas e ficarem sujeitas a uma política de privacidade diferente.</p>
                  <p>Segurança das informações</p>
                  <p>Tomamos medidas de segurança adequadas para a protecção contra o acesso, a alteração, a divulgação e/ou a destruição de dados de forma não autorizada. Procedemos a revisões internas das nossas medidas de segurança e práticas de recolha, armazenamento e processamento de dados, incluindo medidas adequadas de encriptação e segurança física para evitar o acesso não autorizado aos sistemas onde armazenamos dados pessoais.</p>
                  <p>Limitamos o acesso a informações pessoais aos funcionários, que necessitem de conhecer essas informações para as processar em nosso nome. </p>
                  <p>Acesso e atualização de informações pessoais</p>
                  <p>Quanto utiliza os serviços do ELOJOB BRASIL, empreendemos todos os esforços no sentido de lhe proporcionar acesso às suas informações pessoais e de corrigir os seus dados, se estiverem incorretos, ou eliminá-los a seu pedido, caso a sua retenção não seja exigida por lei ou para fins comerciais legítimos. Pedimos aos utilizadores individuais que se identifiquem a si e às informações relativamente às quais solicitam acesso, correção ou remoção antes de processarmos esses pedidos, podendo recusar o processamento de pedidos demasiado repetitivos ou sistemáticos, que requeiram um esforço técnico desproporcionado, que prejudiquem a privacidade de terceiros ou que sejam extremamente difíceis de concretizar (por exemplo, pedidos relativos a informações armazenadas em cassetes para cópias de segurança) ou para os quais o acesso não é necessário. Em qualquer dos casos em que proporcionamos acesso e correção das informações, efetuamos este serviço gratuitamente, exceto se o mesmo implicar um esforço desproporcionado. Devido à forma como mantemos determinados serviços, depois de eliminar as suas informações as cópias residuais podem demorar um determinado período de tempo a serem eliminadas dos nossos servidores ativos e podem permanecer nos nossos sistemas de cópia de segurança. Consulte os Centros de ajuda dos serviços para obter mais informações.</p>
                  <p>Transparência e o direito de escolha</p>
                  <p>No ELOJOB BRASIL, estamos plenamente cientes da confiança que você deposita em nós e da responsabilidade que temos em proteger a sua privacidade. Como parte dessa responsabilidade, informamos quais informações coletamos quando você usa os nossos produtos e serviços, por que nós as coletamos e como as usamos para aprimorar a sua experiência.</p>
                  <p>Nós temos 5 principios de privacidade que descrevem como nós lidamos com a privacidade e com as informações do usuário em todos os nossos produtos:</p>
                  <p>1. Usar as informações para fornecer produtos e serviços relevantes aos nossos usuários.</p>
                  <p>2. Desenvolver produtos que reflitam sólidos padrões e práticas relativos à privacidade.</p>
                  <p>3. Tornar a coleta de informações pessoais transparente.</p>
                  <p>4. Dar aos usuários a oportunidade de fazer escolhas significativas para proteger a própria privacidade.</p>
                  <p>5. Ser um guardião responsável das informações que possuímos.</p>
                  <p>Este Centro de Privacidade foi criado para fornecer a você informações de fácil compreensão sobre os nossos produtos e políticas. Assim, ajudamos você a tomar decisões mais conscientes sobre quais produtos você usa, como usá-los e quais informações fornece para nós.</p>
                  <p>Aplicação</p>
                  <p>O ELOJOB BRASIL revê regularmente a conformidade com a presente Política de privacidade. Quando o ELOJOB BRASIL recebe reclamações formais por escrito, é nossa política contatar o utilizador reclamante relativamente às suas questões. </p>
                  <p>Alterações à presente Política de privacidade</p>
                  <p>Note que a presente Política de privacidade pode ser alterada periodicamente. Não reduziremos os direitos que adquiriu ao abrigo da presente Política de privacidade sem o seu expresso consentimento. Qualquer alteração à Política de privacidade será publicada nesta página e, se as alterações forem significativas, providenciaremos um aviso mais destacado (incluindo, para determinados serviços, notificação por e-mail de alterações à Política de privacidade).</p>
               </div>
            </main>
      <script data-cfasync="false" src="cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="/Template/js/jquery-3.4.1.min.js" type="1c1b3bee51e7ff2306a4b480-text/javascript"></script>
    