            <main role="main" class="col-md-8 ml-sm-auto col-lg-9 px-md-4">
               <div class="overlayzada2"></div>
               <div class="box-geral m-2">
                  <h1 class="titlezada">TERMOS DE USO</h1>
                  <p>Esteja ciente dos termos e condições ao usar nosso site e nosso serviço.</p>
                  <p>O uso do nosso website limita-o aos termos e condições nesta página.</p>
                  <p>Você é totalmente responsável por estar ciente dos nossos termos e respeitar o uso do nosso site e / ou serviço.</p>
                  <p>Se você deseja recusar nossos termos e condições, entre em contato conosco e explique seus motivos.</p>
                  <p>ElojobX está hospedado no site <a href="index.html" class="link-hover">elojobbrasil.com.br</a></p>
                  <p>Todas e quaisquer partes, estão proibidos de usar e ou divulgar dados de quaisquer clientes ou jogadores envolvidos.</p>
                  <p>O cliente estando ciente, aceita todos os riscos e concorda em manter em sigilo quaisquer dados dos profissionais da ElojobX, bem como não estão autorizados a usar ou vincular a empresa ElojobX, respeitando a propriedade intelectual e imagem.</p>
                  <p>ElojobX não reivindica nenhuma afiliação com Riot Games.</p>
                  <p>A ElojobX não reivindica qualquer propriedade intelectual da Riot Games ou de qualquer afiliado. Todos os direitos autorais e marcas registradas são de propriedade de seus respectivos proprietários.</p>
                  <p>O cliente reconhece que ElojobX não tem nenhuma relação com Riot Games. O cliente reconhece que ElojobX não reivindica nenhuma propriedade intelectual da Riot Games ou de outras partes.</p>
                  <p>League of Legends é uma marca registrada da Riot Games, desta forma, a ElojobX não tem afiliação com a associação ou endosso da Riot Games.</p>
                  <p><strong>Deveres do Cliente:</strong></p>
                  <p>ElojobX não está associado com Riot Games ou qualquer outra entidade vinculada a esta.</p>
                  <p>A ElojobX adverte a todas as partes interessadas e potenciais interessados para que se abstenham de violar, infringir ou tomar qualquer ação ilegal relativamente a direitos de propriedade intelectual detidos pela Riot Games ou por qualquer outra entidade vinculada a esta.</p>
                  <p>Ao entrar no nosso site ou em qualquer extensão do nosso site / serviço, incluindo o download e / ou a observação de conteúdo em qualquer plataforma que serve como uma extensão do nosso site ou serviço, você declara sob pena de perjúrio que não está empregado ou afiliado Riot Games e suas respectivas afiliadas e subsidiárias.</p>
                  <p>Ao adquirir ou usar nosso serviço ou qualquer serviço incluído no ElojobX, o cliente reconhece que compreende os serviços que você está comprando e que é responsável por fornecer com precisão as informações necessárias no jogo para que possamos concluir e processar seu pedido.</p>
                  <p>Você, o cliente, reconhece que ao comprar um serviço de reforço da nossa empresa, você não é elegível para proteção do comprador no Paypal, Mercado Pago, ou outra forma eletrônica de pagamento e/ou instituição financeira. </p>
                  <p>Qualquer disputa deve ser mediada através de nosso sistema de suporte. Se você, o cliente, abrir uma disputa com o Paypal, ou outra instituição financeira em relação ao nosso serviço, você está em violação dos nossos termos de serviço.</p>
                  <p>A empresa reserva-se o direito de prosseguir ações contra os clientes que abrirem disputas ou estornos, incluindo a adição das informações do cliente a uma lista de compradores inválidos e a divulgação das suas informações a terceiros.</p>
                  <p>ElojobX reserva-se o direito de prosseguir ações legais contra pessoas que cometeram fraude financeira relacionada com a compra de serviços no nosso site.</p>
                  <p>Você, o cliente, aceita a responsabilidade de perder pontos de liga devido a seus logins, mesmo caindo da série de promoção devido à razão mencionadas, e que os booster tem o direito de mudar suas runas, e que você, cliente aceitar que booster pode usar Influence Point para melhor adaptação e prosseguimento dos trabalhos.</p>
                  <p>Você, o cliente, aceita que não estará jogando nenhum jogo da promoção enquanto o booster não tiver registrado o serviço como terminado, também caso você joga alguns jogos durante a promoção nós reservamos o direito de jogar apenas a série da promoção, sem qualquer garantia.</p>
                  <p>Você, o cliente, aceita que, se você jogar qualquer jogo enquanto tiver comprado uma divisão ou um aumento de tier, reservamos o direito de parar o serviço e anunciar o booster como completo, sem reembolsos oferecidos.</p>
                  <p>Você, o cliente, aceita que se seu ganho de LP estiver abaixo de 12 LP por vitória em qualquer divisão diferente da primeira divisão que você comprou, você terá que pagar valor extra referente a uma divisão da mesma liga, ou nós converteremos seu pedido em vitórias seguindo. Por exemplo, se você comprou prata 3 ao ouro 5 e seu ganho de LP está abaixo de 12 LP por vitória na divisão de prata 2 ou 1, você tem a opção de converter para ganhar ou pagar extra.</p>
                  <p>Você, o cliente, aceita que se você iniciar um estorno você está em violação direta dos termos de uso de ElojobX e legalmente obrigado a fechar o estorno ou pagar o mesmo montante, além de uma taxa determinada pela ElojobX.</p>
                  <p>Você, o cliente, aceita que, se você abrir uma reivindicação após o fim do pedido ou o serviço tiver sido iniciado ou concluído, você está em violação direta dos termos de uso do ElojobX e legalmente obrigado a fechar o pedido ou a pagar de volta o mesmo montante, além de uma taxa determinada pela ElojobX.</p>
                  <p>Você, o cliente, aceita que sua conta será enviada para uma agência de cobradores de dívidas, caso proteste um pagamento feito por um serviço que já havia sido concluído, bem como aceita que você terá que pagar taxas extras cobrindo a agência de cobranças e qualquer outro imprevisto custos em relação ao seu estorno.</p>
                  <p>Ao comprar um serviço você é elegível para um reembolso no prazo de 48 horas de sua compra, isso se aplica se o booster não começar a trabalhar em sua conta dentro do tempo de entrega. Você pode solicitar este reembolso diretamente no Suporte ao Cliente.</p>
                  <p>Os pedidos que não foram concluídos dentro da duração da época de concessão são tratados em conformidade com o ponto “13” destes termos. No caso do booster iniciar os serviços e não conclui-lo dentro do prazo informado no ato da contratação, será emitido um reembolso parcial, em conformidade ao que foi feito.</p>
                  <p>Aos Clientes, reserve o direito de assistir qualquer jogo durante o processo e questionar o booster sobre quaisquer dúvidas, fazendo este por meio do canal de chat do cliente.</p>
                  <p>Aos Clientes, reserve o direito ao se candidatar a um serviço de fila Duo ou a um serviço de coaching o privilégio de um idioma específico para comunicar ao aplicar o serviço, levando em consideração os nossos idiomas disponíveis e, em qualquer caso, o idioma não está disponível, para pedir um tradutor.</p>
                  <p>Aos Clientes, reserve o direito de comprar o Serviço de Elo Boost, Duo Queue's e Coaching detidos pelo ElojobX, consistindo na elevação do montante de elo, o número de duos filas ou o número de horas para o treinador selecionado, isto após o pagamento ser feito.</p>
                  <p>Elo Booster vai contra os termos de serviço da Riot. Isso pode resultar em possíveis ações tomadas contra sua conta. Tomamos todas as precauções necessárias para garantir a sua segurança, mas em última análise, não somos responsáveis por quaisquer ações tomadas contra a sua conta.</p>
                  <p>Você, o cliente, aceita que, se após a compra de um serviço você mostrar inatividade por 28 dias ou mais e não mostrar interesse em encerrar o serviço, vamos fechá-lo e tê-lo como processado.</p>
               </div>
            </main>
   